version: '3.6'

services:
  sonarrr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      -  proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/config
      - ./tv:/tv
      - /mnt/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.example.com`)"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.examplle`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.sonarr-secure.middlewares=secured@file"
      - "traefik.http.routers.sonarr-secure.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
